### ISSUE TITLE
Support mmap syscall in chaosfs

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#220]
## Feature Request

**Is your feature request related to a problem? Please describe:**

chaosfs cannot support mmap syscall currently. So when I tried iochaos with Prometheus, it fails to start because mmap syscall is failed.

```
➜  chaosfs-configmap git:(io-examples) ✗ klo prometheus-788c7ff756-9w46x -c prometheus
level=info ts=2020-02-11T02:26:06.332Z caller=main.go:330 msg="Starting Prometheus" version="(version=2.15.2, branch=HEAD, revision=d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)"
level=info ts=2020-02-11T02:26:06.332Z caller=main.go:331 build_context="(go=go1.13.5, user=root@688433cf4ff7, date=20200106-14:50:51)"
level=info ts=2020-02-11T02:26:06.332Z caller=main.go:332 host_details="(Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 prometheus-788c7ff756-9w46x (none))"
level=info ts=2020-02-11T02:26:06.332Z caller=main.go:333 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-02-11T02:26:06.332Z caller=main.go:334 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-02-11T02:26:06.335Z caller=query_logger.go:107 component=activeQueryTracker msg="Failed to create directory for logging active queries"
level=error ts=2020-02-11T02:26:06.336Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=/var/run/prometheus/data/queries.active err="open /var/run/prometheus/data/queries.active: no such file or directory"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffc22c7ade3, 0x18, 0x14, 0x2c635a0, 0xc00069b650, 0x2c635a0)
	/app/promql/query_logger.go:115 +0x48c
main.main()
	/app/cmd/prometheus/main.go:362 +0x5229
```

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zhouqiang-cl** [comment]
@ethercflow PTAL
