### ISSUE TITLE
Empty target will make controller crash

### ISSUE THREAD

**Issue by YangKeao** [pingcap/chaos-mesh#682]
## Bug Report

I will fix this after #680 merged

```
E0708 07:15:44.236266       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 235 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x150ea00, 0x2421c30)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x150ea00, 0x2421c30)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/pingcap/chaos-mesh/api/v1alpha1.(*Target).GetSelector(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/src/api/v1alpha1/networkchaos_types.go:102 +0x30
github.com/pingcap/chaos-mesh/pkg/utils.SelectAndFilterPods(0x1912e80, 0xc000388200, 0x1924a00, 0xc0004767b0, 0x19023c0, 0x0, 0xc0006bd000, 0x1, 0x1, 0x0, ...)
	/src/pkg/utils/selector.go:56 +0xf6
github.com/pingcap/chaos-mesh/controllers/networkchaos/partition.(*Reconciler).Apply(0xc000074360, 0x1912e80, 0xc000388200, 0xc0001a5089, 0x7, 0xc0003e5c60, 0x19, 0x191c720, 0xc0002b0840, 0x0, ...)
	/src/controllers/networkchaos/partition/types.go:106 +0x1cf
github.com/pingcap/chaos-mesh/controllers/twophase.applyAction(0x1912e80, 0xc000388200, 0xc00075da78, 0xc0001a5089, 0x7, 0xc0003e5c60, 0x19, 0x2540be400, 0x192c8c0, 0xc0002b0840, ...)
	/src/controllers/twophase/types.go:197 +0x207
github.com/pingcap/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile(0xc00075da78, 0xc0001a5089, 0x7, 0xc0003e5c60, 0x19, 0xc0000c0000, 0x0, 0x0, 0x0)
	/src/controllers/twophase/types.go:158 +0x1171
github.com/pingcap/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos(0xc0000f5ca0, 0xc00013e840, 0xc0001a5089, 0x7, 0xc0003e5c60, 0x19, 0x10fca76, 0xc0000af6c0, 0x1912ec0, 0xc000042028)
	/src/controllers/networkchaos/types.go:91 +0x33e
github.com/pingcap/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile(0xc0000f5ca0, 0xc0001a5089, 0x7, 0xc0003e5c60, 0x19, 0xc00013e840, 0x19, 0x18e2dc0, 0xc00013e840, 0x0)
	/src/controllers/networkchaos/types.go:51 +0x267
github.com/pingcap/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile(0xc0000744b0, 0xc0001a5089, 0x7, 0xc0003e5c60, 0x19, 0x0, 0xbfb97a8807c7aa92, 0xc000158510, 0xc0001de128)
	/src/controllers/networkchaos_controller.go:56 +0x1f7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002a8b40, 0x1564160, 0xc00000c580, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x161
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002a8b40, 0x203000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xae
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0002a8b40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003a8130)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003a8130, 0x3b9aca00, 0x0, 0x1, 0xc000278d20)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0003a8130, 0x3b9aca00, 0xc000278d20)
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x305
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x132a770]

```

**Comment by YangKeao** [comment]
Already fixed by #680
